version: '3.10'

services:
  db:
      image: postgres:10
      env_file: database.conf
      ports:
        - "5433:5433"
      volumes:
        - ./db_volume:/var/lib/db
      networks:
        - app-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      FLASK_APP: ./app.py
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  app-network:
    name: app-network
volumes:
  db-data: